// <auto-generated>
/*
 * Regula Document Reader Web API
 *
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Regula.DocumentReader.WebClient.Client;

namespace Regula.DocumentReader.WebClient.Model
{
    /// <summary>
    /// Contains document image.
    /// </summary>
    public partial class DocumentImageResult : ResultItem, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentImageResult" /> class.
        /// </summary>
        /// <param name="rawImageContainer">rawImageContainer</param>
        /// <param name="bufLength">bufLength</param>
        /// <param name="light">light</param>
        /// <param name="listIdx">listIdx</param>
        /// <param name="pageIdx">pageIdx</param>
        [JsonConstructor]
        public DocumentImageResult(ImageData rawImageContainer, Option<int?> bufLength = default, Option<int?> light = default, Option<int?> listIdx = default, Option<int?> pageIdx = default) : base(bufLength, light, listIdx, pageIdx)
        {
            RawImageContainer = rawImageContainer;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets RawImageContainer
        /// </summary>
        [JsonPropertyName("RawImageContainer")]
        public ImageData RawImageContainer { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocumentImageResult {\n");
            sb.Append("  ").Append(base.ToString()?.Replace("\n", "\n  ")).Append("\n");
            sb.Append("  RawImageContainer: ").Append(RawImageContainer).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DocumentImageResult" />
    /// </summary>
    public class DocumentImageResultJsonConverter : JsonConverter<DocumentImageResult>
    {
        /// <summary>
        /// Deserializes json to <see cref="DocumentImageResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DocumentImageResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ImageData?> rawImageContainer = default;
            Option<int?> bufLength = default;
            Option<int?> light = default;
            Option<int?> listIdx = default;
            Option<int?> pageIdx = default;
            Option<int?> resultType = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "RawImageContainer":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                rawImageContainer = new Option<ImageData?>(JsonSerializer.Deserialize<ImageData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "buf_length":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                bufLength = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "light":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                light = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "list_idx":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                listIdx = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "page_idx":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                pageIdx = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "result_type":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                resultType = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!rawImageContainer.IsSet)
                throw new ArgumentException("Property is required for class DocumentImageResult.", nameof(rawImageContainer));

            if (!resultType.IsSet)
                throw new ArgumentException("Property is required for class DocumentImageResult.", nameof(resultType));

            if (rawImageContainer.IsSet && rawImageContainer.Value == null)
                throw new ArgumentNullException(nameof(rawImageContainer), "Property is not nullable for class DocumentImageResult.");

            if (bufLength.IsSet && bufLength.Value == null)
                throw new ArgumentNullException(nameof(bufLength), "Property is not nullable for class DocumentImageResult.");

            if (light.IsSet && light.Value == null)
                throw new ArgumentNullException(nameof(light), "Property is not nullable for class DocumentImageResult.");

            if (listIdx.IsSet && listIdx.Value == null)
                throw new ArgumentNullException(nameof(listIdx), "Property is not nullable for class DocumentImageResult.");

            if (pageIdx.IsSet && pageIdx.Value == null)
                throw new ArgumentNullException(nameof(pageIdx), "Property is not nullable for class DocumentImageResult.");

            if (resultType.IsSet && resultType.Value == null)
                throw new ArgumentNullException(nameof(resultType), "Property is not nullable for class DocumentImageResult.");

            return new DocumentImageResult(rawImageContainer.Value!, bufLength, light, listIdx, pageIdx);
        }

        /// <summary>
        /// Serializes a <see cref="DocumentImageResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="documentImageResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DocumentImageResult documentImageResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, documentImageResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DocumentImageResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="documentImageResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DocumentImageResult documentImageResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (documentImageResult.RawImageContainer == null)
                throw new ArgumentNullException(nameof(documentImageResult.RawImageContainer), "Property is required for class DocumentImageResult.");

            writer.WritePropertyName("RawImageContainer");
            JsonSerializer.Serialize(writer, documentImageResult.RawImageContainer, jsonSerializerOptions);
            if (documentImageResult.BufLengthOption.IsSet)
                writer.WriteNumber("buf_length", documentImageResult.BufLengthOption.Value!.Value);

            if (documentImageResult.LightOption.IsSet)
                writer.WriteNumber("light", documentImageResult.LightOption.Value!.Value);

            if (documentImageResult.ListIdxOption.IsSet)
                writer.WriteNumber("list_idx", documentImageResult.ListIdxOption.Value!.Value);

            if (documentImageResult.PageIdxOption.IsSet)
                writer.WriteNumber("page_idx", documentImageResult.PageIdxOption.Value!.Value);

            writer.WriteNumber("result_type", documentImageResult.ResultType);
        }
    }
}
