/*
 * Regula Document Reader Web API
 *
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 8.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Regula.DocumentReader.WebClient.Client.FileParameter;
using OpenAPIDateConverter = Regula.DocumentReader.WebClient.Client.OpenAPIDateConverter;

namespace Regula.DocumentReader.WebClient.Model
{
    /// <summary>
    /// DocumentTypesCandidatesList
    /// </summary>
    [DataContract(Name = "DocumentTypesCandidatesList")]
    public partial class DocumentTypesCandidatesList : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets RecResult
        /// </summary>
        [DataMember(Name = "RecResult", EmitDefaultValue = false)]
        public DocumentTypeRecognitionResult? RecResult { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentTypesCandidatesList" /> class.
        /// </summary>
        /// <param name="recResult">recResult.</param>
        /// <param name="candidates">candidates.</param>
        public DocumentTypesCandidatesList(DocumentTypeRecognitionResult? recResult = default(DocumentTypeRecognitionResult?), List<OneCandidate> candidates = default(List<OneCandidate>))
        {
            this.RecResult = recResult;
            this.Candidates = candidates;
        }

        /// <summary>
        /// Gets or Sets Candidates
        /// </summary>
        [DataMember(Name = "Candidates", EmitDefaultValue = false)]
        public List<OneCandidate>? Candidates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocumentTypesCandidatesList {\n");
            sb.Append("  RecResult: ").Append(RecResult).Append("\n");
            sb.Append("  Candidates: ").Append(Candidates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
