/*
 * Regula Document Reader Web API
 *
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Regula.DocumentReader.WebClient.Client.FileParameter;
using OpenAPIDateConverter = Regula.DocumentReader.WebClient.Client.OpenAPIDateConverter;

namespace Regula.DocumentReader.WebClient.Model
{
    /// <summary>
    /// Images
    /// </summary>
    [DataContract(Name = "Images")]
    public partial class Images : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Images" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Images() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Images" /> class.
        /// </summary>
        /// <param name="fieldCount">Fields count.</param>
        /// <param name="availableSourceCount">Available sources count.</param>
        /// <param name="availableSourceList">availableSourceList (required).</param>
        /// <param name="fieldList">fieldList (required).</param>
        public Images(int fieldCount = default(int), int availableSourceCount = default(int), List<ImagesAvailableSource> availableSourceList = default(List<ImagesAvailableSource>), List<ImagesField> fieldList = default(List<ImagesField>))
        {
            // to ensure "availableSourceList" is required (not null)
            if (availableSourceList == null)
            {
                throw new ArgumentNullException("availableSourceList is a required property for Images and cannot be null");
            }
            this.AvailableSourceList = availableSourceList;
            // to ensure "fieldList" is required (not null)
            if (fieldList == null)
            {
                throw new ArgumentNullException("fieldList is a required property for Images and cannot be null");
            }
            this.FieldList = fieldList;
            this.FieldCount = fieldCount;
            this.AvailableSourceCount = availableSourceCount;
        }

        /// <summary>
        /// Fields count
        /// </summary>
        /// <value>Fields count</value>
        [DataMember(Name = "fieldCount", EmitDefaultValue = false)]
        public int? FieldCount { get; set; }

        /// <summary>
        /// Available sources count
        /// </summary>
        /// <value>Available sources count</value>
        [DataMember(Name = "availableSourceCount", EmitDefaultValue = false)]
        public int? AvailableSourceCount { get; set; }

        /// <summary>
        /// Gets or Sets AvailableSourceList
        /// </summary>
        [DataMember(Name = "availableSourceList", IsRequired = true, EmitDefaultValue = true)]
        public List<ImagesAvailableSource> AvailableSourceList { get; set; }

        /// <summary>
        /// Gets or Sets FieldList
        /// </summary>
        [DataMember(Name = "fieldList", IsRequired = true, EmitDefaultValue = true)]
        public List<ImagesField> FieldList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Images {\n");
            sb.Append("  FieldCount: ").Append(FieldCount).Append("\n");
            sb.Append("  AvailableSourceCount: ").Append(AvailableSourceCount).Append("\n");
            sb.Append("  AvailableSourceList: ").Append(AvailableSourceList).Append("\n");
            sb.Append("  FieldList: ").Append(FieldList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
