/*
 * Regula Document Reader Web API
 *
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Regula.DocumentReader.WebClient.Client.FileParameter;
using OpenAPIDateConverter = Regula.DocumentReader.WebClient.Client.OpenAPIDateConverter;

namespace Regula.DocumentReader.WebClient.Model
{
    /// <summary>
    /// Enumeration contains a set of constants that define the type of certificate
    /// </summary>
    /// <value>Enumeration contains a set of constants that define the type of certificate</value>
    public enum RFIDPKDResourceType
    {
        /// <summary>
        /// Enum CERTIFICATE_PA for value: 0
        /// </summary>
        CERTIFICATE_PA = 0,

        /// <summary>
        /// Enum CERTIFICATE_TA for value: 1
        /// </summary>
        CERTIFICATE_TA = 1,

        /// <summary>
        /// Enum LDIF for value: 2
        /// </summary>
        LDIF = 2,

        /// <summary>
        /// Enum CRL for value: 3
        /// </summary>
        CRL = 3,

        /// <summary>
        /// Enum ML for value: 4
        /// </summary>
        ML = 4,

        /// <summary>
        /// Enum DEFL for value: 5
        /// </summary>
        DEFL = 5,

        /// <summary>
        /// Enum DEVL for value: 6
        /// </summary>
        DEVL = 6,

        /// <summary>
        /// Enum BL for value: 7
        /// </summary>
        BL = 7
    }

}
