/* 
 * Regula Document Reader Web API
 *
 * Documents recognition as easy as reading two bytes.  # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Regula.DocumentReader.WebClient.Client.OpenAPIDateConverter;

namespace Regula.DocumentReader.WebClient.Model
{
    /// <summary>
    /// Enumeration contains a set of constants that define the type of certificate
    /// </summary>
    /// <value>Enumeration contains a set of constants that define the type of certificate</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum RFIDPKDResourceType
    {
        /// <summary>
        /// Enum CERTIFICATE_PA for value: 0
        /// </summary>
        [EnumMember(Value = "0")]
        CERTIFICATE_PA = 1,

        /// <summary>
        /// Enum CERTIFICATE_TA for value: 1
        /// </summary>
        [EnumMember(Value = "1")]
        CERTIFICATE_TA = 2,

        /// <summary>
        /// Enum LDIF for value: 2
        /// </summary>
        [EnumMember(Value = "2")]
        LDIF = 3,

        /// <summary>
        /// Enum CRL for value: 3
        /// </summary>
        [EnumMember(Value = "3")]
        CRL = 4,

        /// <summary>
        /// Enum ML for value: 4
        /// </summary>
        [EnumMember(Value = "4")]
        ML = 5,

        /// <summary>
        /// Enum DEFL for value: 5
        /// </summary>
        [EnumMember(Value = "5")]
        DEFL = 6,

        /// <summary>
        /// Enum DEVL for value: 6
        /// </summary>
        [EnumMember(Value = "6")]
        DEVL = 7,

        /// <summary>
        /// Enum BL for value: 7
        /// </summary>
        [EnumMember(Value = "7")]
        BL = 8

    }

}
