/*
 * Regula Document Reader Web API
 *
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Regula.DocumentReader.WebClient.Client.FileParameter;
using OpenAPIDateConverter = Regula.DocumentReader.WebClient.Client.OpenAPIDateConverter;

namespace Regula.DocumentReader.WebClient.Model
{
    /// <summary>
    /// Enumeration contains a set of constants specifying the rate of data exchange between the reader and the RFID-chip
    /// </summary>
    /// <value>Enumeration contains a set of constants specifying the rate of data exchange between the reader and the RFID-chip</value>
    public enum RfidBaudRate
    {
        /// <summary>
        /// Enum UNKNOWN for value: 0
        /// </summary>
        UNKNOWN = 0,

        /// <summary>
        /// Enum RFBR_106 for value: 1
        /// </summary>
        RFBR_106 = 1,

        /// <summary>
        /// Enum RFBR_212 for value: 2
        /// </summary>
        RFBR_212 = 2,

        /// <summary>
        /// Enum RFBR_424 for value: 4
        /// </summary>
        RFBR_424 = 4,

        /// <summary>
        /// Enum RFBR_848 for value: 8
        /// </summary>
        RFBR_848 = 8
    }

}
