/* 
 * Regula Document Reader Web API
 *
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Regula.DocumentReader.WebClient.Client.OpenAPIDateConverter;

namespace Regula.DocumentReader.WebClient.Model
{
    /// <summary>
    /// Enumeration contains a set of error codes returned by SDK
    /// </summary>
    /// <value>Enumeration contains a set of error codes returned by SDK</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum RFIDErrorCodes
    {
        /// <summary>
        /// Enum RFID_ERROR_LAYER6_FILE_EOF1 for value: 2147508866
        /// </summary>
        [EnumMember(Value = "2147508866")]
        RFID_ERROR_LAYER6_FILE_EOF1 = 1,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_PWD_DEACTIVATED for value: 2147508867
        /// </summary>
        [EnumMember(Value = "2147508867")]
        RFID_ERROR_LAYER6_PWD_DEACTIVATED = 2,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_PWD_BLOCKED for value: 2147509184
        /// </summary>
        [EnumMember(Value = "2147509184")]
        RFID_ERROR_LAYER6_PWD_BLOCKED = 3,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_PWD_SUSPEND for value: 2147509185
        /// </summary>
        [EnumMember(Value = "2147509185")]
        RFID_ERROR_LAYER6_PWD_SUSPEND = 4,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_PWD_BLOCKED2 for value: 2147510659
        /// </summary>
        [EnumMember(Value = "2147510659")]
        RFID_ERROR_LAYER6_PWD_BLOCKED2 = 5,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_PWD_DEACTIVATED2 for value: 2147510660
        /// </summary>
        [EnumMember(Value = "2147510660")]
        RFID_ERROR_LAYER6_PWD_DEACTIVATED2 = 6,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_PWD_SUSPEND2 for value: 2147510661
        /// </summary>
        [EnumMember(Value = "2147510661")]
        RFID_ERROR_LAYER6_PWD_SUSPEND2 = 7,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_INCORRECT_PARAMS for value: 2147510912
        /// </summary>
        [EnumMember(Value = "2147510912")]
        RFID_ERROR_LAYER6_INCORRECT_PARAMS = 8,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_FILE_NOT_FOUND for value: 2147510914
        /// </summary>
        [EnumMember(Value = "2147510914")]
        RFID_ERROR_LAYER6_FILE_NOT_FOUND = 9,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_NO_REFERENCE_DATA for value: 2147510920
        /// </summary>
        [EnumMember(Value = "2147510920")]
        RFID_ERROR_LAYER6_NO_REFERENCE_DATA = 10,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_FILE_EOF2 for value: 2147511040
        /// </summary>
        [EnumMember(Value = "2147511040")]
        RFID_ERROR_LAYER6_FILE_EOF2 = 11,

        /// <summary>
        /// Enum RFID_ERROR_NO_CHIP_DETECTED for value: 2147549185
        /// </summary>
        [EnumMember(Value = "2147549185")]
        RFID_ERROR_NO_CHIP_DETECTED = 12,

        /// <summary>
        /// Enum RFID_ERROR_NOT_AVAILABLE for value: 2147549186
        /// </summary>
        [EnumMember(Value = "2147549186")]
        RFID_ERROR_NOT_AVAILABLE = 13,

        /// <summary>
        /// Enum RFID_ERROR_INVALID_PARAMETER for value: 2147549188
        /// </summary>
        [EnumMember(Value = "2147549188")]
        RFID_ERROR_INVALID_PARAMETER = 14,

        /// <summary>
        /// Enum RFID_ERROR_NOT_INITIALIZED for value: 2147549189
        /// </summary>
        [EnumMember(Value = "2147549189")]
        RFID_ERROR_NOT_INITIALIZED = 15,

        /// <summary>
        /// Enum RFID_ERROR_NOT_ENOUGH_MEMORY for value: 2147549190
        /// </summary>
        [EnumMember(Value = "2147549190")]
        RFID_ERROR_NOT_ENOUGH_MEMORY = 16,

        /// <summary>
        /// Enum RFID_ERROR_INVALID_DIRECTORY for value: 2147549192
        /// </summary>
        [EnumMember(Value = "2147549192")]
        RFID_ERROR_INVALID_DIRECTORY = 17,

        /// <summary>
        /// Enum RFID_ERROR_UNKNOWN_COMMAND for value: 2147549193
        /// </summary>
        [EnumMember(Value = "2147549193")]
        RFID_ERROR_UNKNOWN_COMMAND = 18,

        /// <summary>
        /// Enum RFID_ERROR_FILE_IO_ERROR for value: 2147549194
        /// </summary>
        [EnumMember(Value = "2147549194")]
        RFID_ERROR_FILE_IO_ERROR = 19,

        /// <summary>
        /// Enum RFID_ERROR_BUSY for value: 2147549195
        /// </summary>
        [EnumMember(Value = "2147549195")]
        RFID_ERROR_BUSY = 20,

        /// <summary>
        /// Enum RFID_ERROR_OLD_FIRMWARE for value: 2147549196
        /// </summary>
        [EnumMember(Value = "2147549196")]
        RFID_ERROR_OLD_FIRMWARE = 21,

        /// <summary>
        /// Enum RFID_ERROR_PCSC_FAILED for value: 2147614720
        /// </summary>
        [EnumMember(Value = "2147614720")]
        RFID_ERROR_PCSC_FAILED = 22,

        /// <summary>
        /// Enum RFID_ERROR_PCSC_READER_NOT_AVAILABLE for value: 2147614721
        /// </summary>
        [EnumMember(Value = "2147614721")]
        RFID_ERROR_PCSC_READER_NOT_AVAILABLE = 23,

        /// <summary>
        /// Enum RFID_ERROR_PCSC_CANT_CONNECT_CARD for value: 2147614722
        /// </summary>
        [EnumMember(Value = "2147614722")]
        RFID_ERROR_PCSC_CANT_CONNECT_CARD = 24,

        /// <summary>
        /// Enum RFID_ERROR_PCSC_CARD_IS_NOT_CONNECTED for value: 2147614723
        /// </summary>
        [EnumMember(Value = "2147614723")]
        RFID_ERROR_PCSC_CARD_IS_NOT_CONNECTED = 25,

        /// <summary>
        /// Enum RFID_ERROR_PCSC_OPERATION_CANCELLED for value: 2147614724
        /// </summary>
        [EnumMember(Value = "2147614724")]
        RFID_ERROR_PCSC_OPERATION_CANCELLED = 26,

        /// <summary>
        /// Enum RFID_ERROR_PCSC_CARD_IS_BUSY for value: 2147614725
        /// </summary>
        [EnumMember(Value = "2147614725")]
        RFID_ERROR_PCSC_CARD_IS_BUSY = 27,

        /// <summary>
        /// Enum RFID_ERROR_PCSC_FAILED_SCARD for value: 2147614726
        /// </summary>
        [EnumMember(Value = "2147614726")]
        RFID_ERROR_PCSC_FAILED_SCARD = 28,

        /// <summary>
        /// Enum RFID_ERROR_PCSC_EXT_LE_FAILED for value: 2147614736
        /// </summary>
        [EnumMember(Value = "2147614736")]
        RFID_ERROR_PCSC_EXT_LE_FAILED = 29,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_PWD_FAILED for value: 2148557760
        /// </summary>
        [EnumMember(Value = "2148557760")]
        RFID_ERROR_LAYER6_PWD_FAILED = 30,

        /// <summary>
        /// Enum RFID_ERROR_NOT_PERFORMED for value: 2197815296
        /// </summary>
        [EnumMember(Value = "2197815296")]
        RFID_ERROR_NOT_PERFORMED = 31,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_IS_CLOSED for value: 2197815297
        /// </summary>
        [EnumMember(Value = "2197815297")]
        RFID_ERROR_SESSION_IS_CLOSED = 32,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_TERMINAL_UNSUPPORTED_OPERATION for value: 2197815298
        /// </summary>
        [EnumMember(Value = "2197815298")]
        RFID_ERROR_SESSION_TERMINAL_UNSUPPORTED_OPERATION = 33,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_TERMINAL_TYPE_UNKNOWN for value: 2197815312
        /// </summary>
        [EnumMember(Value = "2197815312")]
        RFID_ERROR_SESSION_TERMINAL_TYPE_UNKNOWN = 34,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_TERMINAL_TYPE_BAD_CERTIFICATE for value: 2197815313
        /// </summary>
        [EnumMember(Value = "2197815313")]
        RFID_ERROR_SESSION_TERMINAL_TYPE_BAD_CERTIFICATE = 35,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_TERMINAL_TYPE_NOT_SET for value: 2197815314
        /// </summary>
        [EnumMember(Value = "2197815314")]
        RFID_ERROR_SESSION_TERMINAL_TYPE_NOT_SET = 36,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_PROCEDURE_TYPE_UNKNOWN for value: 2197815315
        /// </summary>
        [EnumMember(Value = "2197815315")]
        RFID_ERROR_SESSION_PROCEDURE_TYPE_UNKNOWN = 37,

        /// <summary>
        /// Enum RFID_ERROR_Session_Procedure_Type_Unsupported for value: 2197815316
        /// </summary>
        [EnumMember(Value = "2197815316")]
        RFID_ERROR_Session_Procedure_Type_Unsupported = 38,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_PROCEDURE_TYPE_NOT_SET for value: 2197815317
        /// </summary>
        [EnumMember(Value = "2197815317")]
        RFID_ERROR_SESSION_PROCEDURE_TYPE_NOT_SET = 39,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_KEY_UNKNOWN_TYPE for value: 2197815318
        /// </summary>
        [EnumMember(Value = "2197815318")]
        RFID_ERROR_SESSION_ACCESS_KEY_UNKNOWN_TYPE = 40,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_KEY_UNSUPPORTED_SM_TYPE for value: 2197815319
        /// </summary>
        [EnumMember(Value = "2197815319")]
        RFID_ERROR_SESSION_ACCESS_KEY_UNSUPPORTED_SM_TYPE = 41,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_KEY_INCORRECT_SM_TYPE for value: 2197815320
        /// </summary>
        [EnumMember(Value = "2197815320")]
        RFID_ERROR_SESSION_ACCESS_KEY_INCORRECT_SM_TYPE = 42,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_KEY_RESTRICTED for value: 2197815321
        /// </summary>
        [EnumMember(Value = "2197815321")]
        RFID_ERROR_SESSION_ACCESS_KEY_RESTRICTED = 43,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_KEY_INCORRECT_DATA for value: 2197815322
        /// </summary>
        [EnumMember(Value = "2197815322")]
        RFID_ERROR_SESSION_ACCESS_KEY_INCORRECT_DATA = 44,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_KEY_NOT_SET for value: 2197815323
        /// </summary>
        [EnumMember(Value = "2197815323")]
        RFID_ERROR_SESSION_ACCESS_KEY_NOT_SET = 45,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_PWD_MANAGEMENT_NOT_AUTHORIZED for value: 2197815324
        /// </summary>
        [EnumMember(Value = "2197815324")]
        RFID_ERROR_SESSION_PWD_MANAGEMENT_NOT_AUTHORIZED = 46,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_CONTROL_UNKNOWN_TYPE for value: 2197815328
        /// </summary>
        [EnumMember(Value = "2197815328")]
        RFID_ERROR_SESSION_ACCESS_CONTROL_UNKNOWN_TYPE = 47,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_SM for value: 2197815329
        /// </summary>
        [EnumMember(Value = "2197815329")]
        RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_SM = 48,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_PACE for value: 2197815330
        /// </summary>
        [EnumMember(Value = "2197815330")]
        RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_PACE = 49,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_CA_KEYS for value: 2197815331
        /// </summary>
        [EnumMember(Value = "2197815331")]
        RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_CA_KEYS = 50,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_TA for value: 2197815332
        /// </summary>
        [EnumMember(Value = "2197815332")]
        RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_TA = 51,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_CA for value: 2197815333
        /// </summary>
        [EnumMember(Value = "2197815333")]
        RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_CA = 52,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_CONTROL_INCORRECT_OPTION_CA for value: 2197815334
        /// </summary>
        [EnumMember(Value = "2197815334")]
        RFID_ERROR_SESSION_ACCESS_CONTROL_INCORRECT_OPTION_CA = 53,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_CONTROL_CA_FAILED for value: 2197815335
        /// </summary>
        [EnumMember(Value = "2197815335")]
        RFID_ERROR_SESSION_ACCESS_CONTROL_CA_FAILED = 54,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_CONTROL_TA_FAILED for value: 2197815336
        /// </summary>
        [EnumMember(Value = "2197815336")]
        RFID_ERROR_SESSION_ACCESS_CONTROL_TA_FAILED = 55,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_CONTROL_AA_FAILED for value: 2197815337
        /// </summary>
        [EnumMember(Value = "2197815337")]
        RFID_ERROR_SESSION_ACCESS_CONTROL_AA_FAILED = 56,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_ACCESS_CONTROL_RI_FAILED for value: 2197815338
        /// </summary>
        [EnumMember(Value = "2197815338")]
        RFID_ERROR_SESSION_ACCESS_CONTROL_RI_FAILED = 57,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_PA_SIGNATURE_CHECK_FAILED for value: 2197815344
        /// </summary>
        [EnumMember(Value = "2197815344")]
        RFID_ERROR_SESSION_PA_SIGNATURE_CHECK_FAILED = 58,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_PA_HASH_CHECK_FAILED for value: 2197815345
        /// </summary>
        [EnumMember(Value = "2197815345")]
        RFID_ERROR_SESSION_PA_HASH_CHECK_FAILED = 59,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_INVALID_AUX_DATA_DATE_OF_EXPIRY for value: 2197815360
        /// </summary>
        [EnumMember(Value = "2197815360")]
        RFID_ERROR_SESSION_INVALID_AUX_DATA_DATE_OF_EXPIRY = 60,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_INVALID_AUX_DATA_DATE_OF_BIRTH for value: 2197815361
        /// </summary>
        [EnumMember(Value = "2197815361")]
        RFID_ERROR_SESSION_INVALID_AUX_DATA_DATE_OF_BIRTH = 61,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_INVALID_AUX_DATA_COMMUNITY_ID for value: 2197815362
        /// </summary>
        [EnumMember(Value = "2197815362")]
        RFID_ERROR_SESSION_INVALID_AUX_DATA_COMMUNITY_ID = 62,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_E_SIGN_REQUIRES_APP_SELECTION for value: 2197815376
        /// </summary>
        [EnumMember(Value = "2197815376")]
        RFID_ERROR_SESSION_E_SIGN_REQUIRES_APP_SELECTION = 63,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_E_SIGN_PIN_NOT_SET for value: 2197815377
        /// </summary>
        [EnumMember(Value = "2197815377")]
        RFID_ERROR_SESSION_E_SIGN_PIN_NOT_SET = 64,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_E_SIGN_PIN_NOT_VERIFIED for value: 2197815378
        /// </summary>
        [EnumMember(Value = "2197815378")]
        RFID_ERROR_SESSION_E_SIGN_PIN_NOT_VERIFIED = 65,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_INCORRECT_DATA for value: 2197815392
        /// </summary>
        [EnumMember(Value = "2197815392")]
        RFID_ERROR_SESSION_INCORRECT_DATA = 66,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_FILE_NOT_ENOUGH_DATA for value: 2197880832
        /// </summary>
        [EnumMember(Value = "2197880832")]
        RFID_ERROR_SESSION_FILE_NOT_ENOUGH_DATA = 67,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_FILE_INCORRECT_DATA for value: 2197946368
        /// </summary>
        [EnumMember(Value = "2197946368")]
        RFID_ERROR_SESSION_FILE_INCORRECT_DATA = 68,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_FILE_UNEXPECTED_DATA for value: 2198011904
        /// </summary>
        [EnumMember(Value = "2198011904")]
        RFID_ERROR_SESSION_FILE_UNEXPECTED_DATA = 69,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_FILE_CONTENTS_UNEXPECTED_DATA for value: 2198077440
        /// </summary>
        [EnumMember(Value = "2198077440")]
        RFID_ERROR_SESSION_FILE_CONTENTS_UNEXPECTED_DATA = 70,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_FILE_WRONG_TAG for value: 2198142976
        /// </summary>
        [EnumMember(Value = "2198142976")]
        RFID_ERROR_SESSION_FILE_WRONG_TAG = 71,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_FILE_CANT_USE_DATA for value: 2198208512
        /// </summary>
        [EnumMember(Value = "2198208512")]
        RFID_ERROR_SESSION_FILE_CANT_USE_DATA = 72,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_FILE_CANT_READ_DATA for value: 2198274048
        /// </summary>
        [EnumMember(Value = "2198274048")]
        RFID_ERROR_SESSION_FILE_CANT_READ_DATA = 73,

        /// <summary>
        /// Enum RFID_ERROR_SESSION_FILE_ACCESS_DENIED for value: 2198339584
        /// </summary>
        [EnumMember(Value = "2198339584")]
        RFID_ERROR_SESSION_FILE_ACCESS_DENIED = 74,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_NO_ERROR for value: 2214592512
        /// </summary>
        [EnumMember(Value = "2214592512")]
        RFID_ERROR_LAYER34_NO_ERROR = 75,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_TIME_OUT for value: 2214658048
        /// </summary>
        [EnumMember(Value = "2214658048")]
        RFID_ERROR_LAYER34_TIME_OUT = 76,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_COLLISION for value: 2214723584
        /// </summary>
        [EnumMember(Value = "2214723584")]
        RFID_ERROR_LAYER34_COLLISION = 77,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_CRC for value: 2214789120
        /// </summary>
        [EnumMember(Value = "2214789120")]
        RFID_ERROR_LAYER34_CRC = 78,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_DATA_INTEGRITY for value: 2214854656
        /// </summary>
        [EnumMember(Value = "2214854656")]
        RFID_ERROR_LAYER34_DATA_INTEGRITY = 79,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_DATA_LENGTH for value: 2214920192
        /// </summary>
        [EnumMember(Value = "2214920192")]
        RFID_ERROR_LAYER34_DATA_LENGTH = 80,

        /// <summary>
        /// Enum RFID_ERROR_Layer34_RFU for value: 2214985728
        /// </summary>
        [EnumMember(Value = "2214985728")]
        RFID_ERROR_Layer34_RFU = 81,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_COLLISION_TOO_MANY for value: 2215051264
        /// </summary>
        [EnumMember(Value = "2215051264")]
        RFID_ERROR_LAYER34_COLLISION_TOO_MANY = 82,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_PROTOCOL_B for value: 2215116800
        /// </summary>
        [EnumMember(Value = "2215116800")]
        RFID_ERROR_LAYER34_PROTOCOL_B = 83,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_DATA_CONTENTS for value: 2215182336
        /// </summary>
        [EnumMember(Value = "2215182336")]
        RFID_ERROR_LAYER34_DATA_CONTENTS = 84,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_PROTOCOL for value: 2215247872
        /// </summary>
        [EnumMember(Value = "2215247872")]
        RFID_ERROR_LAYER34_PROTOCOL = 85,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_GLOBAL_TIME_OUT for value: 2215313408
        /// </summary>
        [EnumMember(Value = "2215313408")]
        RFID_ERROR_LAYER34_GLOBAL_TIME_OUT = 86,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_MIFARE_AUTH for value: 2215378944
        /// </summary>
        [EnumMember(Value = "2215378944")]
        RFID_ERROR_LAYER34_MIFARE_AUTH = 87,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_SAM_ERROR for value: 2215444480
        /// </summary>
        [EnumMember(Value = "2215444480")]
        RFID_ERROR_LAYER34_SAM_ERROR = 88,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_SAM_COLLISION for value: 2215510016
        /// </summary>
        [EnumMember(Value = "2215510016")]
        RFID_ERROR_LAYER34_SAM_COLLISION = 89,

        /// <summary>
        /// Enum RFID_ERROR_LAYER34_SAM_ACKNOWLEDGE for value: 2215575552
        /// </summary>
        [EnumMember(Value = "2215575552")]
        RFID_ERROR_LAYER34_SAM_ACKNOWLEDGE = 90,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_SECURITY_MANAGER for value: 2248146944
        /// </summary>
        [EnumMember(Value = "2248146944")]
        RFID_ERROR_LAYER6_SECURITY_MANAGER = 91,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_APP_SELECTION_FAILURE for value: 2248146945
        /// </summary>
        [EnumMember(Value = "2248146945")]
        RFID_ERROR_LAYER6_APP_SELECTION_FAILURE = 92,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_MUTUAL_AUTH_MAC_FAIL for value: 2248147200
        /// </summary>
        [EnumMember(Value = "2248147200")]
        RFID_ERROR_LAYER6_MUTUAL_AUTH_MAC_FAIL = 93,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_MUTUAL_AUTH_ENC_FAIL for value: 2248147201
        /// </summary>
        [EnumMember(Value = "2248147201")]
        RFID_ERROR_LAYER6_MUTUAL_AUTH_ENC_FAIL = 94,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_MUTUAL_AUTH_FAILURE for value: 2248147202
        /// </summary>
        [EnumMember(Value = "2248147202")]
        RFID_ERROR_LAYER6_MUTUAL_AUTH_FAILURE = 95,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_MUTUAL_AUTH_FAILURE_DATA for value: 2248147203
        /// </summary>
        [EnumMember(Value = "2248147203")]
        RFID_ERROR_LAYER6_MUTUAL_AUTH_FAILURE_DATA = 96,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_SM_DO_8E_MISSING for value: 2248147456
        /// </summary>
        [EnumMember(Value = "2248147456")]
        RFID_ERROR_LAYER6_SM_DO_8E_MISSING = 97,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_SM_DO_87_MISSING for value: 2248147457
        /// </summary>
        [EnumMember(Value = "2248147457")]
        RFID_ERROR_LAYER6_SM_DO_87_MISSING = 98,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_SM_DO_99_MISSING for value: 2248147458
        /// </summary>
        [EnumMember(Value = "2248147458")]
        RFID_ERROR_LAYER6_SM_DO_99_MISSING = 99,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_SM_MAC_INCORRECT for value: 2248147459
        /// </summary>
        [EnumMember(Value = "2248147459")]
        RFID_ERROR_LAYER6_SM_MAC_INCORRECT = 100,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_SM_DO_87_INCORRECT for value: 2248147460
        /// </summary>
        [EnumMember(Value = "2248147460")]
        RFID_ERROR_LAYER6_SM_DO_87_INCORRECT = 101,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_NON_TLV_RESPONSE_DATA for value: 2248147712
        /// </summary>
        [EnumMember(Value = "2248147712")]
        RFID_ERROR_LAYER6_NON_TLV_RESPONSE_DATA = 102,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_WRONG_RND_ICC_LENGTH for value: 2248147713
        /// </summary>
        [EnumMember(Value = "2248147713")]
        RFID_ERROR_LAYER6_WRONG_RND_ICC_LENGTH = 103,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_INT_AUTH_FAILURE for value: 2248147714
        /// </summary>
        [EnumMember(Value = "2248147714")]
        RFID_ERROR_LAYER6_INT_AUTH_FAILURE = 104,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_MSE_SET_KAT_FAILURE for value: 2248147715
        /// </summary>
        [EnumMember(Value = "2248147715")]
        RFID_ERROR_LAYER6_MSE_SET_KAT_FAILURE = 105,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_MSE_SET_DST_FAILURE for value: 2248147716
        /// </summary>
        [EnumMember(Value = "2248147716")]
        RFID_ERROR_LAYER6_MSE_SET_DST_FAILURE = 106,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_PSO_CERTIFICATE_FAILURE for value: 2248147717
        /// </summary>
        [EnumMember(Value = "2248147717")]
        RFID_ERROR_LAYER6_PSO_CERTIFICATE_FAILURE = 107,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_MSE_SET_AT_FAILURE for value: 2248147718
        /// </summary>
        [EnumMember(Value = "2248147718")]
        RFID_ERROR_LAYER6_MSE_SET_AT_FAILURE = 108,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_GET_CHALLENGE_FAILURE for value: 2248147719
        /// </summary>
        [EnumMember(Value = "2248147719")]
        RFID_ERROR_LAYER6_GET_CHALLENGE_FAILURE = 109,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_EXT_AUTH_FAILURE for value: 2248147720
        /// </summary>
        [EnumMember(Value = "2248147720")]
        RFID_ERROR_LAYER6_EXT_AUTH_FAILURE = 110,

        /// <summary>
        /// Enum RFID_ERROR_LAYER6_GENERAL_AUTH_FAILURE for value: 2248147721
        /// </summary>
        [EnumMember(Value = "2248147721")]
        RFID_ERROR_LAYER6_GENERAL_AUTH_FAILURE = 111,

        /// <summary>
        /// Enum RFID_ERROR_FAILED for value: 4294967295
        /// </summary>
        [EnumMember(Value = "4294967295")]
        RFID_ERROR_FAILED = 112,

        /// <summary>
        /// Enum RFID_ERROR_NO_ERROR for value: 1
        /// </summary>
        [EnumMember(Value = "1")]
        RFID_ERROR_NO_ERROR = 113,

        /// <summary>
        /// Enum RFID_ERROR_ALREADY_DONE for value: 2
        /// </summary>
        [EnumMember(Value = "2")]
        RFID_ERROR_ALREADY_DONE = 114

    }

}
