/*
 * Regula Document Reader Web API
 *
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Regula.DocumentReader.WebClient.Client.FileParameter;
using OpenAPIDateConverter = Regula.DocumentReader.WebClient.Client.OpenAPIDateConverter;

namespace Regula.DocumentReader.WebClient.Model
{
    /// <summary>
    /// TransactionProcessResult
    /// </summary>
    [DataContract(Name = "TransactionProcessResult")]
    public partial class TransactionProcessResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionProcessResult" /> class.
        /// </summary>
        /// <param name="outData">outData.</param>
        /// <param name="inData">inData.</param>
        /// <param name="tag">tag.</param>
        /// <param name="transactionId">transactionId.</param>
        public TransactionProcessResult(OutData outData = default(OutData), InData inData = default(InData), string tag = default(string), Guid transactionId = default(Guid))
        {
            this.OutData = outData;
            this.InData = inData;
            this.Tag = tag;
            this.TransactionId = transactionId;
        }

        /// <summary>
        /// Gets or Sets OutData
        /// </summary>
        [DataMember(Name = "OutData", EmitDefaultValue = false)]
        public OutData? OutData { get; set; }

        /// <summary>
        /// Gets or Sets InData
        /// </summary>
        [DataMember(Name = "InData", EmitDefaultValue = false)]
        public InData? InData { get; set; }

        /// <summary>
        /// Gets or Sets Tag
        /// </summary>
        [DataMember(Name = "tag", EmitDefaultValue = false)]
        public string? Tag { get; set; }

        /// <summary>
        /// Gets or Sets TransactionId
        /// </summary>
        [DataMember(Name = "transactionId", EmitDefaultValue = false)]
        public Guid? TransactionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransactionProcessResult {\n");
            sb.Append("  OutData: ").Append(OutData).Append("\n");
            sb.Append("  InData: ").Append(InData).Append("\n");
            sb.Append("  Tag: ").Append(Tag).Append("\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
