// <auto-generated>
/*
 * Regula Document Reader Web API
 *
 * Documents recognition as easy as reading two bytes.   # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 7.4.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Regula.DocumentReader.WebClient.Client;

namespace Regula.DocumentReader.WebClient.Model
{
    /// <summary>
    /// Defines VerificationResult
    /// </summary>
    public enum VerificationResult
    {
        /// <summary>
        /// Enum DISABLED for value: 0
        /// </summary>
        DISABLED = 0,

        /// <summary>
        /// Enum VERIFIED for value: 1
        /// </summary>
        VERIFIED = 1,

        /// <summary>
        /// Enum NOT_VERIFIED for value: 2
        /// </summary>
        NOT_VERIFIED = 2,

        /// <summary>
        /// Enum COMPARE_MATCH for value: 3
        /// </summary>
        COMPARE_MATCH = 3,

        /// <summary>
        /// Enum COMPARE_NOT_MATCH for value: 4
        /// </summary>
        COMPARE_NOT_MATCH = 4
    }

    /// <summary>
    /// Converts <see cref="VerificationResult"/> to and from the JSON value
    /// </summary>
    public static class VerificationResultValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="VerificationResult"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static VerificationResult FromString(string value)
        {
            if (value.Equals((0).ToString()))
                return VerificationResult.DISABLED;

            if (value.Equals((1).ToString()))
                return VerificationResult.VERIFIED;

            if (value.Equals((2).ToString()))
                return VerificationResult.NOT_VERIFIED;

            if (value.Equals((3).ToString()))
                return VerificationResult.COMPARE_MATCH;

            if (value.Equals((4).ToString()))
                return VerificationResult.COMPARE_NOT_MATCH;

            throw new NotImplementedException($"Could not convert value to type VerificationResult: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="VerificationResult"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static VerificationResult? FromStringOrDefault(string value)
        {
            if (value.Equals((0).ToString()))
                return VerificationResult.DISABLED;

            if (value.Equals((1).ToString()))
                return VerificationResult.VERIFIED;

            if (value.Equals((2).ToString()))
                return VerificationResult.NOT_VERIFIED;

            if (value.Equals((3).ToString()))
                return VerificationResult.COMPARE_MATCH;

            if (value.Equals((4).ToString()))
                return VerificationResult.COMPARE_NOT_MATCH;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="VerificationResult"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static int ToJsonValue(VerificationResult value)
        {
            return (int) value;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="VerificationResult"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class VerificationResultJsonConverter : JsonConverter<VerificationResult>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override VerificationResult Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            VerificationResult? result = rawValue == null
                ? null
                : VerificationResultValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the VerificationResult to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="verificationResult"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, VerificationResult verificationResult, JsonSerializerOptions options)
        {
            writer.WriteStringValue(verificationResult.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="VerificationResult"/>
    /// </summary>
    public class VerificationResultNullableJsonConverter : JsonConverter<VerificationResult?>
    {
        /// <summary>
        /// Returns a VerificationResult from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override VerificationResult? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            VerificationResult? result = rawValue == null
                ? null
                : VerificationResultValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="verificationResult"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, VerificationResult? verificationResult, JsonSerializerOptions options)
        {
            writer.WriteStringValue(verificationResult?.ToString() ?? "null");
        }
    }
}
