/* 
 * Regula Document Reader Web API
 *
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Regula.OpenApi.WebClient.Model
{
    /// <summary>
    /// Defines CheckResult
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum CheckResult
    {
        /// <summary>
        /// Enum ERROR for value: 0
        /// </summary>
        [EnumMember(Value = "0")]
        ERROR = 1,

        /// <summary>
        /// Enum OK for value: 1
        /// </summary>
        [EnumMember(Value = "1")]
        OK = 2,

        /// <summary>
        /// Enum WAS_NOT_DONE for value: 2
        /// </summary>
        [EnumMember(Value = "2")]
        WAS_NOT_DONE = 3

    }

}
