/* 
 * Regula Document Reader Web API
 *
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Regula.OpenApi.WebClient.Model
{
    /// <summary>
    /// ProcessResponse
    /// </summary>
    [DataContract]
    public partial class ProcessResponse :  IEquatable<ProcessResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessResponse" /> class.
        /// </summary>
        [JsonConstructor]
        protected ProcessResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessResponse" /> class.
        /// </summary>
        /// <param name="chipPage">chipPage (required).</param>
        /// <param name="processingFinished">processingFinished (required).</param>
        /// <param name="containerList">containerList (required).</param>
        /// <param name="transactionInfo">transactionInfo (required).</param>
        public ProcessResponse(int chipPage = default(int), int processingFinished = default(int), ContainerList containerList = default(ContainerList), TransactionInfo transactionInfo = default(TransactionInfo))
        {
            // to ensure "chipPage" is required (not null)
            if (chipPage == null)
            {
                throw new InvalidDataException("chipPage is a required property for ProcessResponse and cannot be null");
            }
            else
            {
                this.ChipPage = chipPage;
            }
            
            // to ensure "processingFinished" is required (not null)
            if (processingFinished == null)
            {
                throw new InvalidDataException("processingFinished is a required property for ProcessResponse and cannot be null");
            }
            else
            {
                this.ProcessingFinished = processingFinished;
            }
            
            // to ensure "containerList" is required (not null)
            if (containerList == null)
            {
                throw new InvalidDataException("containerList is a required property for ProcessResponse and cannot be null");
            }
            else
            {
                this.ContainerList = containerList;
            }
            
            // to ensure "transactionInfo" is required (not null)
            if (transactionInfo == null)
            {
                throw new InvalidDataException("transactionInfo is a required property for ProcessResponse and cannot be null");
            }
            else
            {
                this.TransactionInfo = transactionInfo;
            }
            
        }
        
        /// <summary>
        /// Gets or Sets ChipPage
        /// </summary>
        [DataMember(Name="ChipPage", EmitDefaultValue=true)]
        public int ChipPage { get; set; }

        /// <summary>
        /// Gets or Sets ProcessingFinished
        /// </summary>
        [DataMember(Name="ProcessingFinished", EmitDefaultValue=true)]
        public int ProcessingFinished { get; set; }

        /// <summary>
        /// Gets or Sets ContainerList
        /// </summary>
        [DataMember(Name="ContainerList", EmitDefaultValue=true)]
        public ContainerList ContainerList { get; set; }

        /// <summary>
        /// Gets or Sets TransactionInfo
        /// </summary>
        [DataMember(Name="TransactionInfo", EmitDefaultValue=true)]
        public TransactionInfo TransactionInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProcessResponse {\n");
            sb.Append("  ChipPage: ").Append(ChipPage).Append("\n");
            sb.Append("  ProcessingFinished: ").Append(ProcessingFinished).Append("\n");
            sb.Append("  ContainerList: ").Append(ContainerList).Append("\n");
            sb.Append("  TransactionInfo: ").Append(TransactionInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProcessResponse);
        }

        /// <summary>
        /// Returns true if ProcessResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ProcessResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProcessResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ChipPage == input.ChipPage ||
                    (this.ChipPage != null &&
                    this.ChipPage.Equals(input.ChipPage))
                ) && 
                (
                    this.ProcessingFinished == input.ProcessingFinished ||
                    (this.ProcessingFinished != null &&
                    this.ProcessingFinished.Equals(input.ProcessingFinished))
                ) && 
                (
                    this.ContainerList == input.ContainerList ||
                    (this.ContainerList != null &&
                    this.ContainerList.Equals(input.ContainerList))
                ) && 
                (
                    this.TransactionInfo == input.TransactionInfo ||
                    (this.TransactionInfo != null &&
                    this.TransactionInfo.Equals(input.TransactionInfo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ChipPage != null)
                    hashCode = hashCode * 59 + this.ChipPage.GetHashCode();
                if (this.ProcessingFinished != null)
                    hashCode = hashCode * 59 + this.ProcessingFinished.GetHashCode();
                if (this.ContainerList != null)
                    hashCode = hashCode * 59 + this.ContainerList.GetHashCode();
                if (this.TransactionInfo != null)
                    hashCode = hashCode * 59 + this.TransactionInfo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
