/* 
 * Regula Document Reader Web API
 *
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Regula.OpenApi.WebClient.Model
{
    /// <summary>
    /// Document data sources
    /// </summary>
    /// <value>Document data sources</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public static class Source
    {
        public const string MRZ = "MRZ";
        public const string VISUAL = "VISUAL";
        public const string BARCODE = "BARCODE";
        public const string RFID = "RFID";
        public const string MAGNETIC = "MAGNETIC";
    }
}
