version: "3.9"

services:
  docreader:
    image: regulaforensics/docreader:latest
    volumes:
      - ./regula.license:/app/extBin/unix_x64/cpu/regula.license
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - docreader