name: publish maven package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.6.0
        with:
          dotnet-version: '3.1.x'
      - run: dotnet pack src/Regula.DocumentReader.WebClient -c Release -p:PackageVersion=${{github.event.release.name}}
      - run: dotnet nuget push src/Regula.DocumentReader.WebClient/bin/Release/Regula.DocumentReader.WebClient.${{github.event.release.name}}.nupkg -k ${{secrets.NUGET_AUTH_TOKEN}} -s https://api.nuget.org/v3/index.json
