name: publish nuget package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - run: dotnet pack src/Regula.DocumentReader.WebClient -c Release -p:PackageVersion=${{github.event.release.name}} -p:Version=${{github.event.release.name}}
      - run: dotnet nuget push src/Regula.DocumentReader.WebClient/bin/Release/Regula.DocumentReader.WebClient.${{github.event.release.name}}.nupkg -k ${{secrets.NUGET_AUTH_TOKEN}} -s https://api.nuget.org/v3/index.json
