name: run smoke test

on:
  pull_request:
    branches:
      - develop
      - master
      - stable

env:
  API_BASE_PATH: "https://nightly-api.regulaforensics.com"
  TEST_LICENSE: ${{secrets.TEST_LICENSE}}

jobs:
  run_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |            
            8.0.x
      - name: Build
        run: |
          dotnet build src/Regula.DocumentReader.NetCoreExample -c Release
          dotnet build src/Regula.DocumentReader.NetCoreExamplePortraitComparison -c Release    
        
      - name: Run basic sample
        run: ./Regula.DocumentReader.NetCoreExample
        working-directory: src/Regula.DocumentReader.NetCoreExample/bin/Release/net8.0/
          
      - name: Run Portrait comparison
        run: ./Regula.DocumentReader.NetCoreExamplePortraitComparison
        working-directory: src/Regula.DocumentReader.NetCoreExamplePortraitComparison/bin/Release/net8.0/        
